export const COLLEGE_GE_SUBJECTS = [
  "Mathematics in the Modern World",
  "Purposive Communication",
  "Understanding the Self",
  "Readings in Philippine History",
  "The Contemporary World",
  "Life and Works of Jose Rizal",
  "Physical Education 1",
  "Physical Education 2",
  "Ethics",
  "Art Appreciation",
  "Science, Technology, and Society",
  "NSTP 1",
  "NSTP 2",
] as const

export const SHS_MINOR_SUBJECTS = [
  "Oral Communication", "Reading and Writing Skills", "Mathematics in the Modern World",
  "Understanding the Self", "Contemporary World", "Readings in Philippine History",
  "Physical Education / Health", "Life and Works of Jose Rizal", "National Service Training Program (NSTP)",
  "Art Appreciation",
] as const

export const COLLEGE_GE_SET = new Set<string>(COLLEGE_GE_SUBJECTS)
export const SHS_MINOR_SET = new Set<string>(SHS_MINOR_SUBJECTS)

export const COLLEGE_GE_LEVEL: Record<string, string> = {
  "Mathematics in the Modern World":  "1st Year",
  "Purposive Communication":          "1st Year",
  "Understanding the Self":           "1st Year",
  "Readings in Philippine History":   "1st Year",
  "The Contemporary World":           "1st Year",
  "Life and Works of Jose Rizal":     "1st Year",
  "Physical Education 1":             "1st Year",
  "Physical Education 2":             "2nd Year",
  "Ethics":                           "2nd Year",
  "Art Appreciation":                 "2nd Year",
  "Science, Technology, and Society": "2nd Year",
  "NSTP 1":                           "2nd Year",
  "NSTP 2":                           "2nd Year",
}

export const SHS_MINOR_LEVEL: Record<string, string> = {
  "Oral Communication":                       "Grade 11",
  "Reading and Writing Skills":               "Grade 11",
  "Mathematics in the Modern World":          "Grade 11",
  "Understanding the Self":                   "Grade 11",
  "Contemporary World":                       "Grade 11",
  "Readings in Philippine History":           "Grade 11",
  "Physical Education / Health":              "Grade 11",
  "Life and Works of Jose Rizal":             "Grade 11",
  "National Service Training Program (NSTP)": "Grade 12",
  "Art Appreciation":                         "Grade 12",
}

export const LEVEL_SUBJECTS: Record<string, string[]> = {
  "Daycare 1": [
    "Language and Literacy", "Cognitive and Numeracy Skills", "Physical Development, Health, and Safety",
    "Social and Emotional Development", "Creative Arts and Music", "Understanding the World / Discovery",
  ],
  "Daycare 2": [
    "Language and Literacy", "Cognitive and Numeracy Skills", "Physical Development, Health, and Safety",
    "Social and Emotional Development", "Creative Arts and Music", "Understanding the World / Discovery",
  ],
  "Kinder 1": [
    "Language, Literacy, and Communication", "Mathematical Thinking", "Physical Development, Health, and Safety",
    "Social and Emotional Development / Values Formation", "Creative Arts", "Understanding the World / Discovery",
  ],
  "Kinder 2": [
    "Language, Literacy, and Communication", "Mathematical Thinking", "Physical Development, Health, and Safety",
    "Social and Emotional Development / Values Formation", "Creative Arts", "Understanding the World / Discovery",
  ],
  "Grade 1":  ["English","Mathematics","Science","Filipino","Araling Panlipunan","MAPEH","Edukasyon sa Pagpapakatao (ESP)"],
  "Grade 2":  ["English","Mathematics","Science","Filipino","Araling Panlipunan","MAPEH","Edukasyon sa Pagpapakatao (ESP)"],
  "Grade 3":  ["English","Mathematics","Science","Filipino","Araling Panlipunan","MAPEH","Edukasyon sa Pagpapakatao (ESP)"],
  "Grade 4":  ["English","Mathematics","Science","Filipino","Araling Panlipunan","MAPEH","Edukasyon sa Pagpapakatao (ESP)"],
  "Grade 5":  ["English","Mathematics","Science","Filipino","Araling Panlipunan","MAPEH","Edukasyon sa Pagpapakatao (ESP)"],
  "Grade 6":  ["English","Mathematics","Science","Filipino","Araling Panlipunan","MAPEH","Edukasyon sa Pagpapakatao (ESP)"],
  "Grade 7":  ["English","Mathematics","Science","Filipino","Araling Panlipunan","MAPEH","Edukasyon sa Pagpapakatao (ESP)","TLE"],
  "Grade 8":  ["English","Mathematics","Science","Filipino","Araling Panlipunan","MAPEH","Edukasyon sa Pagpapakatao (ESP)","TLE"],
  "Grade 9":  ["English","Mathematics","Science","Filipino","Araling Panlipunan","MAPEH","Edukasyon sa Pagpapakatao (ESP)","TLE"],
  "Grade 10": ["English","Mathematics","Science","Filipino","Araling Panlipunan","MAPEH","Edukasyon sa Pagpapakatao (ESP)","TLE"],
}

export const SUBJECT_SEP = "::"

export function subjectKey(groupName: string, subjectName: string): string {
  return `${groupName}${SUBJECT_SEP}${subjectName}`
}

export function parseSubjectKey(key: string): { groupName: string; subjectName: string } {
  const idx = key.indexOf(SUBJECT_SEP)
  if (idx === -1) return { groupName: "", subjectName: key }
  return {
    groupName:   key.slice(0, idx),
    subjectName: key.slice(idx + SUBJECT_SEP.length),
  }
}

export const SHS_STRAND_SUBJECTS: Record<string, string[]> = {
  ABM: [
    "Oral Communication","Reading and Writing Skills","Mathematics in the Modern World",
    "Understanding the Self","Contemporary World","Readings in Philippine History",
    "Physical Education / Health","Life and Works of Jose Rizal",
    "National Service Training Program (NSTP)","Art Appreciation",
    "Fundamentals of Accounting","Business Math","Fundamentals of Economics",
    "Principles of Management","Entrepreneurship","Organization and Management",
    "Business Finance","Business Ethics","Applied Economics","Strategic Business Planning",
  ],
  STEM: [
    "Oral Communication","Reading and Writing Skills","Mathematics in the Modern World",
    "Understanding the Self","Contemporary World","Readings in Philippine History",
    "Physical Education / Health","Life and Works of Jose Rizal",
    "National Service Training Program (NSTP)","Art Appreciation",
    "General Biology","General Chemistry","General Physics","Earth and Life Science",
    "Calculus and Analytical Geometry","Advanced Physics","Organic Chemistry",
    "Research in Science","Engineering and Technology Applications","Applied Mathematics",
  ],
  HUMSS: [
    "Oral Communication","Reading and Writing Skills","Mathematics in the Modern World",
    "Understanding the Self","Contemporary World","Readings in Philippine History",
    "Physical Education / Health","Life and Works of Jose Rizal",
    "National Service Training Program (NSTP)","Art Appreciation",
    "Introduction to Philosophy","Understanding Culture and Society","Creative Writing",
    "Philippine Politics and Governance","Psychology","Social Research and Statistics",
    "World History and Globalization","Philosophy of Human Person",
    "Economics for Social Sciences","Applied Social Sciences / Ethics in Society",
  ],
  GAS: [
    "Oral Communication","Reading and Writing Skills","Mathematics in the Modern World",
    "Understanding the Self","Contemporary World","Readings in Philippine History",
    "Physical Education / Health","Life and Works of Jose Rizal",
    "National Service Training Program (NSTP)","Art Appreciation",
    "Introduction to Humanities","Introduction to Social Sciences",
    "Fundamentals of Business and Management","Basic Principles of Science and Technology",
    "Creative Writing","Introduction to Philosophy","Research Methods / Applied Research",
    "Economics / Business Economics","Social Issues and Ethics","Interdisciplinary Elective",
  ],
  ICT: [
    "Oral Communication","Reading and Writing Skills","Mathematics in the Modern World",
    "Understanding the Self","Contemporary World","Readings in Philippine History",
    "Physical Education / Health","Life and Works of Jose Rizal",
    "National Service Training Program (NSTP)","Art Appreciation",
    "Computer Programming 1","Introduction to Computing","Web Development 1 (HTML, CSS)",
    "Computer Programming 2","Web Development 2 (JavaScript)","Database Management Systems",
    "Systems Analysis and Design","Mobile Application Development",
    "Computer Networks and Security","Capstone Project","ICT Project Management",
    "Emerging Technologies in ICT",
  ],
  HE: [
    "Oral Communication","Reading and Writing Skills","Mathematics in the Modern World",
    "Understanding the Self","Contemporary World","Readings in Philippine History",
    "Physical Education / Health","Life and Works of Jose Rizal",
    "National Service Training Program (NSTP)","Art Appreciation",
    "Introduction to Home Economics","Cookery / Culinary Basics","Bread and Pastry Production",
    "Food and Beverage Services","Housekeeping","Caregiving (Basic)","Dressmaking / Tailoring",
    "Advanced Cookery / International Cuisine","Events Management Services",
    "Entrepreneurship in Home Economics","Work Immersion (OJT)","Capstone Project / Practical Assessment",
  ],
  IA: [
    "Oral Communication","Reading and Writing Skills","Mathematics in the Modern World",
    "Understanding the Self","Contemporary World","Readings in Philippine History",
    "Physical Education / Health","Life and Works of Jose Rizal",
    "National Service Training Program (NSTP)","Art Appreciation",
    "Introduction to Industrial Arts","Basic Electrical Installation and Maintenance",
    "Carpentry Fundamentals","Shielded Metal Arc Welding (SMAW) NC I","Plumbing Basics",
    "Automotive Servicing NC I","Electrical Installation and Maintenance NC II",
    "Shielded Metal Arc Welding (SMAW) NC II","Advanced Carpentry / Construction Technology",
    "Industrial Safety and Maintenance","Work Immersion (OJT)","Capstone Project / Practical Assessment",
  ],
  "Agri-Fishery": [
    "Oral Communication","Reading and Writing Skills","Mathematics in the Modern World",
    "Understanding the Self","Contemporary World","Readings in Philippine History",
    "Physical Education / Health","Life and Works of Jose Rizal",
    "National Service Training Program (NSTP)","Art Appreciation",
    "Introduction to Agri-Fishery Arts","Crop Production (Basic)","Animal Production (Basic)",
    "Aquaculture (Basic)","Horticulture","Agricultural Machinery and Tools",
    "Crop Production NC II","Animal Production NC II","Aquaculture NC II","Farm Management",
    "Work Immersion (OJT)","Capstone Project / Practical Assessment",
  ],
  Sports: [
    "Oral Communication","Reading and Writing Skills","Mathematics in the Modern World",
    "Understanding the Self","Contemporary World","Readings in Philippine History",
    "Physical Education / Health","Life and Works of Jose Rizal",
    "National Service Training Program (NSTP)","Art Appreciation",
    "Introduction to Sports Science","Physical Fitness and Conditioning",
    "Fundamentals of Coaching","Sports Officiating and Rules","Sports Psychology",
    "Safety and First Aid in Sports","Advanced Coaching and Training Techniques",
    "Sports Event Management","Anatomy and Physiology for Athletes",
    "Sports Analytics and Performance Analysis","Work Immersion (OJT)",
    "Capstone Project / Practical Assessment",
  ],
  "Arts and Design": [
    "Oral Communication","Reading and Writing Skills","Mathematics in the Modern World",
    "Understanding the Self","Contemporary World","Readings in Philippine History",
    "Physical Education / Health","Life and Works of Jose Rizal",
    "National Service Training Program (NSTP)","Art Appreciation",
    "Introduction to Arts and Design","Elements and Principles of Design",
    "Creative Industries I (Applied Arts)","Creative Industries II (Media Arts)",
    "Fundamentals of Performing Arts","Visual Arts Production","Specialization in Arts",
    "Portfolio Development","Arts Production and Management","Contemporary Arts Practices",
    "Work Immersion (OJT)","Capstone Project / Culminating Exhibit",
  ],
}

export const COURSE_SUBJECTS: Record<string, string[]> = {
  BSIT: [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "Introduction to Computing","Computer Programming 1","Computer Programming 2",
    "Data Structures and Algorithms","Database Management Systems",
    "Web Systems and Technologies","Software Engineering","Human-Computer Interaction",
    "Operating Systems","Computer Networks","Information Assurance and Security",
    "Systems Analysis and Design","IT Project Management","Capstone Project / Thesis",
  ],
  BSBA: [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "Principles of Management","Microeconomics","Macroeconomics","Business Statistics",
    "Principles of Marketing","Financial Management","Business Law",
    "Human Resource Management","Operations Management","Business Ethics",
    "Organizational Behavior","Strategic Management","International Business",
    "Entrepreneurial Management","Business Research","Project Management",
  ],
  BSA: [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "Fundamentals of Accounting","Financial Accounting and Reporting I","Business Law",
    "Management Accounting","Regulatory Framework and Legal Issues in Business",
    "Cost Accounting","Accounting Information Systems","Auditing Theory",
    "Advanced Financial Accounting and Reporting","Financial Management",
    "Auditing and Assurance Services","Taxation (Income Tax, Business Tax)",
    "Strategic Cost Management",
    "Governance, Business Ethics, Risk Management, and Internal Control",
    "Accounting Research","Integrated Review Courses (Board Exam Preparation)",
    "Advanced Taxation","CPA Licensure Exam Review",
  ],
  BSCS: [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "Introduction to Computing","Computer Programming 1","Computer Programming 2",
    "Discrete Mathematics","Object-Oriented Programming","Computer Architecture",
    "Data Structures and Algorithms","Database Systems","Algorithms and Complexity",
    "Automata Theory","Operating Systems","Numerical Methods","Programming Languages",
    "Software Engineering","Computer Networks","Human-Computer Interaction",
    "Artificial Intelligence","Machine Learning","CS Thesis / Capstone Project",
  ],
  BSHM: [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "Introduction to Hospitality Industry","Food and Beverage Service Operations",
    "Housekeeping Operations","Front Office Operations","Culinary Arts / Basic Cooking",
    "Hospitality Marketing","Hospitality Financial Management","Food Safety and Sanitation",
    "Hospitality Law","Customer Service Management","Tourism Planning and Development",
    "Hotel and Restaurant Management","Beverage Management (Bar and Drinks)",
    "Event Management","Banquet and Catering Management","Entrepreneurship in Hospitality",
    "Internship / OJT",
  ],
  BSCRIM: [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "Introduction to Criminology","Criminal Law","Criminological Theories",
    "Law Enforcement Administration","Ethics and Moral Values in Law Enforcement",
    "Criminalistics / Forensic Science","Crime Detection and Investigation",
    "Juvenile Delinquency","Police Administration","Criminal Psychology",
    "Correctional Administration","Disaster and Risk Management",
    "Research in Criminology","Criminal Investigation Practicum",
    "Community Policing and Public Safety",
  ],
  BSTM: [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "Principles of Tourism","Tourism Research and Statistics",
    "Tourism Planning and Development","Travel Agency Operations",
    "Tour Guiding and Tour Operations","Hospitality and Tourism Law",
    "Tourism Marketing and Promotion","Event and Convention Management",
    "Sustainable Tourism","Cultural and Heritage Tourism",
    "Tourism Policy and Governance","Airline and Cruise Management",
    "Tourism Entrepreneurship","Internship / OJT",
  ],
  BSED: [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "The Teaching Profession","Foundations of Education","Child and Adolescent Development",
    "Principles of Teaching","Facilitating Learner-Centered Teaching",
    "Educational Technology","Assessment of Learning 1","Assessment of Learning 2",
    "Curriculum Development","Field Study (Practice Teaching Preparation)",
    "Practice Teaching / Internship",
  ],
  "BSED-ENG": [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "The Teaching Profession","Foundations of Education","Child and Adolescent Development",
    "Principles of Teaching","Facilitating Learner-Centered Teaching",
    "Educational Technology","Assessment of Learning 1","Assessment of Learning 2",
    "Curriculum Development","Field Study (Practice Teaching Preparation)",
    "Practice Teaching / Internship"
  ],
  "BSED-MATH": [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "The Teaching Profession","Foundations of Education","Child and Adolescent Development",
    "Principles of Teaching","Facilitating Learner-Centered Teaching",
    "Educational Technology","Assessment of Learning 1","Assessment of Learning 2",
    "Curriculum Development","Field Study (Practice Teaching Preparation)",
    "Practice Teaching / Internship"
  ],
  "BSED-SCI": [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "The Teaching Profession","Foundations of Education","Child and Adolescent Development",
    "Principles of Teaching","Facilitating Learner-Centered Teaching",
    "Educational Technology","Assessment of Learning 1","Assessment of Learning 2",
    "Curriculum Development","Field Study (Practice Teaching Preparation)",
    "Practice Teaching / Internship"
  ],
  "BSED-SS": [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "The Teaching Profession","Foundations of Education","Child and Adolescent Development",
    "Principles of Teaching","Facilitating Learner-Centered Teaching",
    "Educational Technology","Assessment of Learning 1","Assessment of Learning 2",
    "Curriculum Development","Field Study (Practice Teaching Preparation)",
    "Practice Teaching / Internship"
  ],
  "BSED-FIL": [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "The Teaching Profession","Foundations of Education","Child and Adolescent Development",
    "Principles of Teaching","Facilitating Learner-Centered Teaching",
    "Educational Technology","Assessment of Learning 1","Assessment of Learning 2",
    "Curriculum Development","Field Study (Practice Teaching Preparation)",
    "Practice Teaching / Internship"
  ],
  "BSED-TLE": [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "The Teaching Profession","Foundations of Education","Child and Adolescent Development",
    "Principles of Teaching","Facilitating Learner-Centered Teaching",
    "Educational Technology","Assessment of Learning 1","Assessment of Learning 2",
    "Curriculum Development","Field Study (Practice Teaching Preparation)",
    "Practice Teaching / Internship"
  ],
}
