export const COLLEGE_GE_SUBJECTS = [
  "Mathematics in the Modern World",
  "Purposive Communication",
  "Understanding the Self",
  "Readings in Philippine History",
  "The Contemporary World",
  "Life and Works of Jose Rizal",
  "Physical Education 1",
  "Physical Education 2",
  "Ethics",
  "Art Appreciation",
  "Science, Technology, and Society",
  "NSTP 1",
  "NSTP 2",
] as const

export const SHS_MINOR_SUBJECTS = [
  "Oral Communication", "Reading and Writing Skills", "Mathematics in the Modern World",
  "Understanding the Self", "Contemporary World", "Readings in Philippine History",
  "Physical Education / Health", "Life and Works of Jose Rizal", "National Service Training Program (NSTP)",
  "Art Appreciation",
] as const

export const COLLEGE_GE_SET = new Set<string>(COLLEGE_GE_SUBJECTS)
export const SHS_MINOR_SET = new Set<string>(SHS_MINOR_SUBJECTS)

export const COLLEGE_GE_LEVEL: Record<string, string> = {
  "Mathematics in the Modern World":  "1st Year",
  "Purposive Communication":          "1st Year",
  "Understanding the Self":           "1st Year",
  "Readings in Philippine History":   "1st Year",
  "The Contemporary World":           "1st Year",
  "Life and Works of Jose Rizal":     "1st Year",
  "Physical Education 1":             "1st Year",
  "Physical Education 2":             "1st Year",
  "Ethics":                           "2nd Year",
  "Art Appreciation":                 "2nd Year",
  "Science, Technology, and Society": "2nd Year",
  "NSTP 1":                           "2nd Year",
  "NSTP 2":                           "2nd Year",
}

export const SHS_MINOR_LEVEL: Record<string, string> = {
  "Oral Communication":                       "Grade 11",
  "Reading and Writing Skills":               "Grade 11",
  "Mathematics in the Modern World":          "Grade 11",
  "Understanding the Self":                   "Grade 11",
  "Contemporary World":                       "Grade 11",
  "Readings in Philippine History":           "Grade 11",
  "Physical Education / Health":              "Grade 11",
  "Life and Works of Jose Rizal":             "Grade 11",
  "National Service Training Program (NSTP)": "Grade 12",
  "Art Appreciation":                         "Grade 12",
}

export const UNASSIGNED_YEAR = "Unassigned Year"

const BSED_MAJOR_YEARS: Record<string, string> = {
  "The Teaching Profession":                "1st Year",
  "Foundations of Education":               "1st Year",
  "Child and Adolescent Development":       "2nd Year",
  "Principles of Teaching":                 "2nd Year",
  "Facilitating Learner-Centered Teaching": "2nd Year",
  "Educational Technology":                 "2nd Year",
  "Assessment of Learning 1":               "3rd Year",
  "Assessment of Learning 2":               "3rd Year",
  "Curriculum Development":                 "3rd Year",
  "Field Study (Practice Teaching Preparation)": "3rd Year",
  "Practice Teaching / Internship":         "4th Year",
}

export const COURSE_SUBJECT_YEARS: Record<string, Record<string, string>> = {
  BSIT: {
    "Introduction to Computing":      "1st Year",
    "Computer Programming 1":         "1st Year",
    "Computer Programming 2":         "1st Year",
    "Data Structures and Algorithms": "2nd Year",
    "Database Management Systems":    "2nd Year",
    "Web Systems and Technologies":   "2nd Year",
    "Software Engineering":           "3rd Year",
    "Human-Computer Interaction":     "3rd Year",
    "Operating Systems":              "3rd Year",
    "Computer Networks":              "3rd Year",
    "Information Assurance and Security": "3rd Year",
    "Systems Analysis and Design":    "3rd Year",
    "IT Project Management":          "4th Year",
    "Capstone Project / Thesis":      "4th Year",
  },
  BSBA: {
    "Principles of Management":  "1st Year",
    "Microeconomics":            "1st Year",
    "Macroeconomics":            "1st Year",
    "Business Statistics":       "1st Year",
    "Principles of Marketing":   "2nd Year",
    "Financial Management":      "2nd Year",
    "Business Law":              "2nd Year",
    "Human Resource Management": "2nd Year",
    "Operations Management":     "2nd Year",
    "Business Ethics":           "2nd Year",
    "Organizational Behavior":   "2nd Year",
    "Strategic Management":      "3rd Year",
    "International Business":    "3rd Year",
    "Entrepreneurial Management": "3rd Year",
    "Business Research":         "3rd Year",
    "Project Management":        "4th Year",
  },
  BSA: {
    "Fundamentals of Accounting":                     "1st Year",
    "Financial Accounting and Reporting I":           "1st Year",
    "Business Law":                                   "2nd Year",
    "Management Accounting":                          "2nd Year",
    "Regulatory Framework and Legal Issues in Business": "2nd Year",
    "Cost Accounting":                                "2nd Year",
    "Accounting Information Systems":                 "2nd Year",
    "Auditing Theory":                                "3rd Year",
    "Advanced Financial Accounting and Reporting":    "3rd Year",
    "Financial Management":                           "3rd Year",
    "Auditing and Assurance Services":                "3rd Year",
    "Taxation (Income Tax, Business Tax)":            "3rd Year",
    "Strategic Cost Management":                      "4th Year",
    "Governance, Business Ethics, Risk Management, and Internal Control": "4th Year",
    "Accounting Research":                            "4th Year",
    "Integrated Review Courses (Board Exam Preparation)": "4th Year",
    "Advanced Taxation":                              "5th Year",
    "CPA Licensure Exam Review":                      "5th Year",
  },
  BSCS: {
    "Introduction to Computing":                    "1st Year",
    "Computer Programming 1":                       "1st Year",
    "Computer Programming 2":                       "1st Year",
    "Discrete Mathematics":                         "1st Year",
    "Object-Oriented Programming":                  "2nd Year",
    "Computer Architecture":                        "2nd Year",
    "Data Structures and Algorithms":               "2nd Year",
    "Database Systems":                             "2nd Year",
    "Algorithms and Complexity":                    "3rd Year",
    "Automata Theory":                              "3rd Year",
    "Operating Systems":                            "3rd Year",
    "Numerical Methods":                            "3rd Year",
    "Programming Languages":                        "3rd Year",
    "Software Engineering":                         "3rd Year",
    "Computer Networks":                            "3rd Year",
    "Human-Computer Interaction":                   "3rd Year",
    "Artificial Intelligence":                      "4th Year",
    "Machine Learning":                             "4th Year",
    "CS Thesis / Capstone Project":                 "4th Year",
  },
  BSHM: {
    "Introduction to Hospitality Industry":         "1st Year",
    "Food and Beverage Service Operations":         "1st Year",
    "Housekeeping Operations":                      "1st Year",
    "Front Office Operations":                      "2nd Year",
    "Culinary Arts / Basic Cooking":                "2nd Year",
    "Hospitality Marketing":                        "2nd Year",
    "Hospitality Financial Management":             "2nd Year",
    "Food Safety and Sanitation":                   "2nd Year",
    "Hospitality Law":                              "2nd Year",
    "Customer Service Management":                  "2nd Year",
    "Tourism Planning and Development":             "3rd Year",
    "Hotel and Restaurant Management":              "3rd Year",
    "Beverage Management (Bar and Drinks)":         "3rd Year",
    "Event Management":                             "3rd Year",
    "Banquet and Catering Management":              "3rd Year",
    "Entrepreneurship in Hospitality":              "4th Year",
    "Internship / OJT":                             "4th Year",
  },
  BSCRIM: {
    "Introduction to Criminology":                "1st Year",
    "Criminal Law":                               "1st Year",
    "Criminological Theories":                    "2nd Year",
    "Law Enforcement Administration":             "2nd Year",
    "Ethics and Moral Values in Law Enforcement": "2nd Year",
    "Criminalistics / Forensic Science":          "2nd Year",
    "Crime Detection and Investigation":          "2nd Year",
    "Juvenile Delinquency":                       "2nd Year",
    "Police Administration":                      "3rd Year",
    "Criminal Psychology":                        "3rd Year",
    "Correctional Administration":                "3rd Year",
    "Disaster and Risk Management":               "3rd Year",
    "Research in Criminology":                    "3rd Year",
    "Criminal Investigation Practicum":           "4th Year",
    "Community Policing and Public Safety":       "4th Year",
  },
  BSTM: {
    "Principles of Tourism":            "1st Year",
    "Tourism Research and Statistics":  "2nd Year",
    "Tourism Planning and Development": "2nd Year",
    "Travel Agency Operations":         "2nd Year",
    "Tour Guiding and Tour Operations": "2nd Year",
    "Hospitality and Tourism Law":      "2nd Year",
    "Tourism Marketing and Promotion":  "3rd Year",
    "Event and Convention Management":  "3rd Year",
    "Sustainable Tourism":              "3rd Year",
    "Cultural and Heritage Tourism":    "3rd Year",
    "Tourism Policy and Governance":    "3rd Year",
    "Airline and Cruise Management":    "4th Year",
    "Tourism Entrepreneurship":         "4th Year",
    "Internship / OJT":                 "4th Year",
  },
  BSED: BSED_MAJOR_YEARS,
  "BSED-ENG": BSED_MAJOR_YEARS,
  "BSED-MATH": BSED_MAJOR_YEARS,
  "BSED-SCI": BSED_MAJOR_YEARS,
  "BSED-SS": BSED_MAJOR_YEARS,
  "BSED-FIL": BSED_MAJOR_YEARS,
  "BSED-TLE": BSED_MAJOR_YEARS,
}

export const SHS_MAJOR_YEARS: Record<string, Record<string, string>> = {
  ABM: {
    "Fundamentals of Accounting":  "Grade 11",
    "Business Math":               "Grade 11",
    "Fundamentals of Economics":   "Grade 11",
    "Principles of Management":    "Grade 11",
    "Entrepreneurship":            "Grade 12",
    "Organization and Management": "Grade 12",
    "Business Finance":            "Grade 12",
    "Business Ethics":             "Grade 12",
    "Applied Economics":           "Grade 12",
    "Strategic Business Planning": "Grade 12",
  },
  STEM: {
    "General Biology":                         "Grade 11",
    "General Chemistry":                       "Grade 11",
    "General Physics":                         "Grade 11",
    "Earth and Life Science":                  "Grade 11",
    "Calculus and Analytical Geometry":        "Grade 12",
    "Advanced Physics":                        "Grade 12",
    "Organic Chemistry":                       "Grade 12",
    "Research in Science":                     "Grade 12",
    "Engineering and Technology Applications": "Grade 12",
    "Applied Mathematics":                     "Grade 12",
  },
  HUMSS: {
    "Introduction to Philosophy":           "Grade 11",
    "Understanding Culture and Society":    "Grade 11",
    "Creative Writing":                     "Grade 11",
    "Philippine Politics and Governance":   "Grade 11",
    "Psychology":                           "Grade 12",
    "Social Research and Statistics":       "Grade 12",
    "World History and Globalization":      "Grade 12",
    "Philosophy of Human Person":           "Grade 12",
    "Economics for Social Sciences":        "Grade 12",
    "Applied Social Sciences / Ethics in Society": "Grade 12",
  },
  GAS: {
    "Introduction to Humanities":                 "Grade 11",
    "Introduction to Social Sciences":            "Grade 11",
    "Fundamentals of Business and Management":    "Grade 11",
    "Basic Principles of Science and Technology": "Grade 11",
    "Creative Writing":                           "Grade 12",
    "Introduction to Philosophy":                 "Grade 12",
    "Research Methods / Applied Research":        "Grade 12",
    "Economics / Business Economics":             "Grade 12",
    "Social Issues and Ethics":                   "Grade 12",
    "Interdisciplinary Elective":                 "Grade 12",
  },
  ICT: {
    "Computer Programming 1":               "Grade 11",
    "Introduction to Computing":            "Grade 11",
    "Web Development 1 (HTML, CSS)":        "Grade 11",
    "Computer Programming 2":               "Grade 11",
    "Web Development 2 (JavaScript)":       "Grade 11",
    "Database Management Systems":          "Grade 11",
    "Systems Analysis and Design":          "Grade 12",
    "Mobile Application Development":       "Grade 12",
    "Computer Networks and Security":       "Grade 12",
    "Capstone Project":                     "Grade 12",
    "ICT Project Management":               "Grade 12",
    "Emerging Technologies in ICT":         "Grade 12",
  },
  HE: {
    "Introduction to Home Economics":           "Grade 11",
    "Cookery / Culinary Basics":                "Grade 11",
    "Bread and Pastry Production":              "Grade 11",
    "Food and Beverage Services":               "Grade 11",
    "Housekeeping":                             "Grade 11",
    "Caregiving (Basic)":                       "Grade 11",
    "Dressmaking / Tailoring":                  "Grade 12",
    "Advanced Cookery / International Cuisine": "Grade 12",
    "Events Management Services":               "Grade 12",
    "Entrepreneurship in Home Economics":       "Grade 12",
    "Work Immersion (OJT)":                     "Grade 12",
    "Capstone Project / Practical Assessment":  "Grade 12",
  },
  IA: {
    "Introduction to Industrial Arts":               "Grade 11",
    "Basic Electrical Installation and Maintenance": "Grade 11",
    "Carpentry Fundamentals":                        "Grade 11",
    "Shielded Metal Arc Welding (SMAW) NC I":        "Grade 11",
    "Plumbing Basics":                               "Grade 11",
    "Automotive Servicing NC I":                     "Grade 11",
    "Electrical Installation and Maintenance NC II": "Grade 12",
    "Shielded Metal Arc Welding (SMAW) NC II":       "Grade 12",
    "Advanced Carpentry / Construction Technology":  "Grade 12",
    "Industrial Safety and Maintenance":             "Grade 12",
    "Work Immersion (OJT)":                          "Grade 12",
    "Capstone Project / Practical Assessment":       "Grade 12",
  },
  "Agri-Fishery": {
    "Introduction to Agri-Fishery Arts":  "Grade 11",
    "Crop Production (Basic)":            "Grade 11",
    "Animal Production (Basic)":          "Grade 11",
    "Aquaculture (Basic)":                "Grade 11",
    "Horticulture":                       "Grade 11",
    "Agricultural Machinery and Tools":   "Grade 11",
    "Crop Production NC II":              "Grade 12",
    "Animal Production NC II":            "Grade 12",
    "Aquaculture NC II":                  "Grade 12",
    "Farm Management":                    "Grade 12",
    "Work Immersion (OJT)":               "Grade 12",
    "Capstone Project / Practical Assessment": "Grade 12",
  },
  Sports: {
    "Introduction to Sports Science":            "Grade 11",
    "Physical Fitness and Conditioning":         "Grade 11",
    "Fundamentals of Coaching":                  "Grade 11",
    "Sports Officiating and Rules":              "Grade 11",
    "Sports Psychology":                         "Grade 11",
    "Safety and First Aid in Sports":            "Grade 11",
    "Advanced Coaching and Training Techniques": "Grade 12",
    "Sports Event Management":                   "Grade 12",
    "Anatomy and Physiology for Athletes":       "Grade 12",
    "Sports Analytics and Performance Analysis": "Grade 12",
    "Work Immersion (OJT)":                      "Grade 12",
    "Capstone Project / Practical Assessment":   "Grade 12",
  },
  "Arts and Design": {
    "Introduction to Arts and Design":        "Grade 11",
    "Elements and Principles of Design":      "Grade 11",
    "Creative Industries I (Applied Arts)":   "Grade 11",
    "Creative Industries II (Media Arts)":    "Grade 11",
    "Fundamentals of Performing Arts":        "Grade 11",
    "Visual Arts Production":                 "Grade 11",
    "Specialization in Arts":                 "Grade 12",
    "Portfolio Development":                  "Grade 12",
    "Arts Production and Management":         "Grade 12",
    "Contemporary Arts Practices":            "Grade 12",
    "Work Immersion (OJT)":                   "Grade 12",
    "Capstone Project / Culminating Exhibit": "Grade 12",
  },
}

export const LEVEL_SUBJECTS: Record<string, string[]> = {
  "Daycare 1": [
    "Language and Literacy", "Cognitive and Numeracy Skills", "Physical Development, Health, and Safety",
    "Social and Emotional Development", "Creative Arts and Music", "Understanding the World / Discovery",
  ],
  "Daycare 2": [
    "Language and Literacy", "Cognitive and Numeracy Skills", "Physical Development, Health, and Safety",
    "Social and Emotional Development", "Creative Arts and Music", "Understanding the World / Discovery",
  ],
  "Kinder 1": [
    "Language, Literacy, and Communication", "Mathematical Thinking", "Physical Development, Health, and Safety",
    "Social and Emotional Development / Values Formation", "Creative Arts", "Understanding the World / Discovery",
  ],
  "Kinder 2": [
    "Language, Literacy, and Communication", "Mathematical Thinking", "Physical Development, Health, and Safety",
    "Social and Emotional Development / Values Formation", "Creative Arts", "Understanding the World / Discovery",
  ],
  "Grade 1":  ["English","Mathematics","Science","Filipino","Araling Panlipunan","MAPEH","Edukasyon sa Pagpapakatao (ESP)"],
  "Grade 2":  ["English","Mathematics","Science","Filipino","Araling Panlipunan","MAPEH","Edukasyon sa Pagpapakatao (ESP)"],
  "Grade 3":  ["English","Mathematics","Science","Filipino","Araling Panlipunan","MAPEH","Edukasyon sa Pagpapakatao (ESP)"],
  "Grade 4":  ["English","Mathematics","Science","Filipino","Araling Panlipunan","MAPEH","Edukasyon sa Pagpapakatao (ESP)"],
  "Grade 5":  ["English","Mathematics","Science","Filipino","Araling Panlipunan","MAPEH","Edukasyon sa Pagpapakatao (ESP)"],
  "Grade 6":  ["English","Mathematics","Science","Filipino","Araling Panlipunan","MAPEH","Edukasyon sa Pagpapakatao (ESP)"],
  "Grade 7":  ["English","Mathematics","Science","Filipino","Araling Panlipunan","MAPEH","Edukasyon sa Pagpapakatao (ESP)","TLE"],
  "Grade 8":  ["English","Mathematics","Science","Filipino","Araling Panlipunan","MAPEH","Edukasyon sa Pagpapakatao (ESP)","TLE"],
  "Grade 9":  ["English","Mathematics","Science","Filipino","Araling Panlipunan","MAPEH","Edukasyon sa Pagpapakatao (ESP)","TLE"],
  "Grade 10": ["English","Mathematics","Science","Filipino","Araling Panlipunan","MAPEH","Edukasyon sa Pagpapakatao (ESP)","TLE"],
}

export const SUBJECT_SEP = "::"

export function subjectKey(groupName: string, subjectName: string): string {
  return `${groupName}${SUBJECT_SEP}${subjectName}`
}

export function parseSubjectKey(key: string): { groupName: string; subjectName: string } {
  const idx = key.indexOf(SUBJECT_SEP)
  if (idx === -1) return { groupName: "", subjectName: key }
  return {
    groupName:   key.slice(0, idx),
    subjectName: key.slice(idx + SUBJECT_SEP.length),
  }
}

export const SHS_STRAND_SUBJECTS: Record<string, string[]> = {
  ABM: [
    "Oral Communication","Reading and Writing Skills","Mathematics in the Modern World",
    "Understanding the Self","Contemporary World","Readings in Philippine History",
    "Physical Education / Health","Life and Works of Jose Rizal",
    "National Service Training Program (NSTP)","Art Appreciation",
    "Fundamentals of Accounting","Business Math","Fundamentals of Economics",
    "Principles of Management","Entrepreneurship","Organization and Management",
    "Business Finance","Business Ethics","Applied Economics","Strategic Business Planning",
  ],
  STEM: [
    "Oral Communication","Reading and Writing Skills","Mathematics in the Modern World",
    "Understanding the Self","Contemporary World","Readings in Philippine History",
    "Physical Education / Health","Life and Works of Jose Rizal",
    "National Service Training Program (NSTP)","Art Appreciation",
    "General Biology","General Chemistry","General Physics","Earth and Life Science",
    "Calculus and Analytical Geometry","Advanced Physics","Organic Chemistry",
    "Research in Science","Engineering and Technology Applications","Applied Mathematics",
  ],
  HUMSS: [
    "Oral Communication","Reading and Writing Skills","Mathematics in the Modern World",
    "Understanding the Self","Contemporary World","Readings in Philippine History",
    "Physical Education / Health","Life and Works of Jose Rizal",
    "National Service Training Program (NSTP)","Art Appreciation",
    "Introduction to Philosophy","Understanding Culture and Society","Creative Writing",
    "Philippine Politics and Governance","Psychology","Social Research and Statistics",
    "World History and Globalization","Philosophy of Human Person",
    "Economics for Social Sciences","Applied Social Sciences / Ethics in Society",
  ],
  GAS: [
    "Oral Communication","Reading and Writing Skills","Mathematics in the Modern World",
    "Understanding the Self","Contemporary World","Readings in Philippine History",
    "Physical Education / Health","Life and Works of Jose Rizal",
    "National Service Training Program (NSTP)","Art Appreciation",
    "Introduction to Humanities","Introduction to Social Sciences",
    "Fundamentals of Business and Management","Basic Principles of Science and Technology",
    "Creative Writing","Introduction to Philosophy","Research Methods / Applied Research",
    "Economics / Business Economics","Social Issues and Ethics","Interdisciplinary Elective",
  ],
  ICT: [
    "Oral Communication","Reading and Writing Skills","Mathematics in the Modern World",
    "Understanding the Self","Contemporary World","Readings in Philippine History",
    "Physical Education / Health","Life and Works of Jose Rizal",
    "National Service Training Program (NSTP)","Art Appreciation",
    "Computer Programming 1","Introduction to Computing","Web Development 1 (HTML, CSS)",
    "Computer Programming 2","Web Development 2 (JavaScript)","Database Management Systems",
    "Systems Analysis and Design","Mobile Application Development",
    "Computer Networks and Security","Capstone Project","ICT Project Management",
    "Emerging Technologies in ICT",
  ],
  HE: [
    "Oral Communication","Reading and Writing Skills","Mathematics in the Modern World",
    "Understanding the Self","Contemporary World","Readings in Philippine History",
    "Physical Education / Health","Life and Works of Jose Rizal",
    "National Service Training Program (NSTP)","Art Appreciation",
    "Introduction to Home Economics","Cookery / Culinary Basics","Bread and Pastry Production",
    "Food and Beverage Services","Housekeeping","Caregiving (Basic)","Dressmaking / Tailoring",
    "Advanced Cookery / International Cuisine","Events Management Services",
    "Entrepreneurship in Home Economics","Work Immersion (OJT)","Capstone Project / Practical Assessment",
  ],
  IA: [
    "Oral Communication","Reading and Writing Skills","Mathematics in the Modern World",
    "Understanding the Self","Contemporary World","Readings in Philippine History",
    "Physical Education / Health","Life and Works of Jose Rizal",
    "National Service Training Program (NSTP)","Art Appreciation",
    "Introduction to Industrial Arts","Basic Electrical Installation and Maintenance",
    "Carpentry Fundamentals","Shielded Metal Arc Welding (SMAW) NC I","Plumbing Basics",
    "Automotive Servicing NC I","Electrical Installation and Maintenance NC II",
    "Shielded Metal Arc Welding (SMAW) NC II","Advanced Carpentry / Construction Technology",
    "Industrial Safety and Maintenance","Work Immersion (OJT)","Capstone Project / Practical Assessment",
  ],
  "Agri-Fishery": [
    "Oral Communication","Reading and Writing Skills","Mathematics in the Modern World",
    "Understanding the Self","Contemporary World","Readings in Philippine History",
    "Physical Education / Health","Life and Works of Jose Rizal",
    "National Service Training Program (NSTP)","Art Appreciation",
    "Introduction to Agri-Fishery Arts","Crop Production (Basic)","Animal Production (Basic)",
    "Aquaculture (Basic)","Horticulture","Agricultural Machinery and Tools",
    "Crop Production NC II","Animal Production NC II","Aquaculture NC II","Farm Management",
    "Work Immersion (OJT)","Capstone Project / Practical Assessment",
  ],
  Sports: [
    "Oral Communication","Reading and Writing Skills","Mathematics in the Modern World",
    "Understanding the Self","Contemporary World","Readings in Philippine History",
    "Physical Education / Health","Life and Works of Jose Rizal",
    "National Service Training Program (NSTP)","Art Appreciation",
    "Introduction to Sports Science","Physical Fitness and Conditioning",
    "Fundamentals of Coaching","Sports Officiating and Rules","Sports Psychology",
    "Safety and First Aid in Sports","Advanced Coaching and Training Techniques",
    "Sports Event Management","Anatomy and Physiology for Athletes",
    "Sports Analytics and Performance Analysis","Work Immersion (OJT)",
    "Capstone Project / Practical Assessment",
  ],
  "Arts and Design": [
    "Oral Communication","Reading and Writing Skills","Mathematics in the Modern World",
    "Understanding the Self","Contemporary World","Readings in Philippine History",
    "Physical Education / Health","Life and Works of Jose Rizal",
    "National Service Training Program (NSTP)","Art Appreciation",
    "Introduction to Arts and Design","Elements and Principles of Design",
    "Creative Industries I (Applied Arts)","Creative Industries II (Media Arts)",
    "Fundamentals of Performing Arts","Visual Arts Production","Specialization in Arts",
    "Portfolio Development","Arts Production and Management","Contemporary Arts Practices",
    "Work Immersion (OJT)","Capstone Project / Culminating Exhibit",
  ],
}

export const COURSE_SUBJECTS: Record<string, string[]> = {
  BSIT: [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "Introduction to Computing","Computer Programming 1","Computer Programming 2",
    "Data Structures and Algorithms","Database Management Systems",
    "Web Systems and Technologies","Software Engineering","Human-Computer Interaction",
    "Operating Systems","Computer Networks","Information Assurance and Security",
    "Systems Analysis and Design","IT Project Management","Capstone Project / Thesis",
  ],
  BSBA: [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "Principles of Management","Microeconomics","Macroeconomics","Business Statistics",
    "Principles of Marketing","Financial Management","Business Law",
    "Human Resource Management","Operations Management","Business Ethics",
    "Organizational Behavior","Strategic Management","International Business",
    "Entrepreneurial Management","Business Research","Project Management",
  ],
  BSA: [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "Fundamentals of Accounting","Financial Accounting and Reporting I","Business Law",
    "Management Accounting","Regulatory Framework and Legal Issues in Business",
    "Cost Accounting","Accounting Information Systems","Auditing Theory",
    "Advanced Financial Accounting and Reporting","Financial Management",
    "Auditing and Assurance Services","Taxation (Income Tax, Business Tax)",
    "Strategic Cost Management",
    "Governance, Business Ethics, Risk Management, and Internal Control",
    "Accounting Research","Integrated Review Courses (Board Exam Preparation)",
    "Advanced Taxation","CPA Licensure Exam Review",
  ],
  BSCS: [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "Introduction to Computing","Computer Programming 1","Computer Programming 2",
    "Discrete Mathematics","Object-Oriented Programming","Computer Architecture",
    "Data Structures and Algorithms","Database Systems","Algorithms and Complexity",
    "Automata Theory","Operating Systems","Numerical Methods","Programming Languages",
    "Software Engineering","Computer Networks","Human-Computer Interaction",
    "Artificial Intelligence","Machine Learning","CS Thesis / Capstone Project",
  ],
  BSHM: [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "Introduction to Hospitality Industry","Food and Beverage Service Operations",
    "Housekeeping Operations","Front Office Operations","Culinary Arts / Basic Cooking",
    "Hospitality Marketing","Hospitality Financial Management","Food Safety and Sanitation",
    "Hospitality Law","Customer Service Management","Tourism Planning and Development",
    "Hotel and Restaurant Management","Beverage Management (Bar and Drinks)",
    "Event Management","Banquet and Catering Management","Entrepreneurship in Hospitality",
    "Internship / OJT",
  ],
  BSCRIM: [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "Introduction to Criminology","Criminal Law","Criminological Theories",
    "Law Enforcement Administration","Ethics and Moral Values in Law Enforcement",
    "Criminalistics / Forensic Science","Crime Detection and Investigation",
    "Juvenile Delinquency","Police Administration","Criminal Psychology",
    "Correctional Administration","Disaster and Risk Management",
    "Research in Criminology","Criminal Investigation Practicum",
    "Community Policing and Public Safety",
  ],
  BSTM: [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "Principles of Tourism","Tourism Research and Statistics",
    "Tourism Planning and Development","Travel Agency Operations",
    "Tour Guiding and Tour Operations","Hospitality and Tourism Law",
    "Tourism Marketing and Promotion","Event and Convention Management",
    "Sustainable Tourism","Cultural and Heritage Tourism",
    "Tourism Policy and Governance","Airline and Cruise Management",
    "Tourism Entrepreneurship","Internship / OJT",
  ],
  BSED: [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "The Teaching Profession","Foundations of Education","Child and Adolescent Development",
    "Principles of Teaching","Facilitating Learner-Centered Teaching",
    "Educational Technology","Assessment of Learning 1","Assessment of Learning 2",
    "Curriculum Development","Field Study (Practice Teaching Preparation)",
    "Practice Teaching / Internship",
  ],
  "BSED-ENG": [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "The Teaching Profession","Foundations of Education","Child and Adolescent Development",
    "Principles of Teaching","Facilitating Learner-Centered Teaching",
    "Educational Technology","Assessment of Learning 1","Assessment of Learning 2",
    "Curriculum Development","Field Study (Practice Teaching Preparation)",
    "Practice Teaching / Internship"
  ],
  "BSED-MATH": [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "The Teaching Profession","Foundations of Education","Child and Adolescent Development",
    "Principles of Teaching","Facilitating Learner-Centered Teaching",
    "Educational Technology","Assessment of Learning 1","Assessment of Learning 2",
    "Curriculum Development","Field Study (Practice Teaching Preparation)",
    "Practice Teaching / Internship"
  ],
  "BSED-SCI": [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "The Teaching Profession","Foundations of Education","Child and Adolescent Development",
    "Principles of Teaching","Facilitating Learner-Centered Teaching",
    "Educational Technology","Assessment of Learning 1","Assessment of Learning 2",
    "Curriculum Development","Field Study (Practice Teaching Preparation)",
    "Practice Teaching / Internship"
  ],
  "BSED-SS": [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "The Teaching Profession","Foundations of Education","Child and Adolescent Development",
    "Principles of Teaching","Facilitating Learner-Centered Teaching",
    "Educational Technology","Assessment of Learning 1","Assessment of Learning 2",
    "Curriculum Development","Field Study (Practice Teaching Preparation)",
    "Practice Teaching / Internship"
  ],
  "BSED-FIL": [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "The Teaching Profession","Foundations of Education","Child and Adolescent Development",
    "Principles of Teaching","Facilitating Learner-Centered Teaching",
    "Educational Technology","Assessment of Learning 1","Assessment of Learning 2",
    "Curriculum Development","Field Study (Practice Teaching Preparation)",
    "Practice Teaching / Internship"
  ],
  "BSED-TLE": [
    "Mathematics in the Modern World","Purposive Communication",
    "Understanding the Self","Readings in Philippine History","The Contemporary World",
    "Life and Works of Jose Rizal",
    "Physical Education 1","Physical Education 2",
    "Ethics","Art Appreciation",
    "Science, Technology, and Society",
    "NSTP 1","NSTP 2",
    "The Teaching Profession","Foundations of Education","Child and Adolescent Development",
    "Principles of Teaching","Facilitating Learner-Centered Teaching",
    "Educational Technology","Assessment of Learning 1","Assessment of Learning 2",
    "Curriculum Development","Field Study (Practice Teaching Preparation)",
    "Practice Teaching / Internship"
  ],
}
