export const PAGE_SIZE = 20;

export const ADMIN_ACTION_OPTIONS: { value: string; label: string }[] = [
  { value: "all",                        label: "All Actions" },
  { value: "org_created",                label: "Org Created" },
  { value: "org_updated",                label: "Org Updated" },
  { value: "org_seeded",                 label: "Org Seeded" },
  { value: "school_year_created",        label: "School Year Created" },
  { value: "school_year_updated",        label: "School Year Updated" },
  { value: "school_year_activated",      label: "School Year Activated" },
  { value: "school_year_ended",          label: "School Year Ended" },
  { value: "program_created",            label: "Department Created" },
  { value: "program_updated",            label: "Department Updated" },
  { value: "program_deleted",            label: "Department Deleted" },
  { value: "section_created",            label: "Section Created" },
  { value: "section_updated",            label: "Section Updated" },
  { value: "section_deleted",            label: "Section Deleted" },
  { value: "class_created",              label: "Class Created" },
  { value: "class_archived",             label: "Class Archived" },
  { value: "class_reassigned",           label: "Class Reassigned" },
  { value: "student_profile_changed",    label: "Student Profile Changed" },
  { value: "student_status_changed",     label: "Student Status Changed" },
  { value: "enrollment_created",         label: "Enrollment Created" },
  { value: "enrollment_removed",         label: "Enrollment Removed" },
  { value: "enrollment_updated",         label: "Enrollment Updated" },
  { value: "password_reset",             label: "Password Reset" },
  { value: "grade_lock_override",        label: "Grade Lock Override" },
  { value: "section_capacity_overflow",  label: "Section Capacity Overflow" },
  { value: "class_capacity_overflow",    label: "Class Capacity Overflow" },
  { value: "academic_calendar_changed",  label: "Academic Calendar Changed" },
  { value: "GRADE_LOCK",                 label: "Grade Lock" },
  { value: "GRADE_UNLOCK_OVERRIDE",      label: "Grade Unlock Override" },
  { value: "AUTO_GRADE_LOCK",            label: "Auto Grade Lock" },
];

export const ACTIVITY_ACTION_OPTIONS: { value: string; label: string }[] = [
  { value: "all",                           label: "All Actions" },
  { value: "enrollment_created",            label: "Enrollment Created" },
  { value: "enrollment_removed",            label: "Enrollment Removed" },
  { value: "meeting_started",               label: "Meeting Started" },
  { value: "meeting_ended",                 label: "Meeting Ended" },
  { value: "assessment_created",            label: "Assessment Created" },
  { value: "assessment_edited",             label: "Assessment Edited" },
  { value: "assessment_published",          label: "Assessment Published" },
  { value: "assessment_deleted",            label: "Assessment Deleted" },
  { value: "score_published",               label: "Score Published" },
  { value: "score_unpublished",             label: "Score Unpublished" },
  { value: "grade_locked",                  label: "Grade Locked" },
  { value: "lesson_created",                label: "Lesson Created" },
  { value: "lesson_updated",                label: "Lesson Updated" },
  { value: "concept_extraction_requested",  label: "Concept Extraction Requested" },
  { value: "concept_extraction_completed",  label: "Concept Extraction Completed" },
  { value: "class_reassigned",              label: "Class Reassigned" },
];
