// Must be first: assessment.dto.ts uses class-validator decorators, which need
// reflect-metadata registered (the sibling assessment-type.constants.spec.ts
// does the same).
import 'reflect-metadata';
import {
  ASSESSMENT_TYPE_VALUES,
  MANUAL_ONLY_TYPES,
  SYSTEM_GRADABLE_TYPES,
  isSystemGradable,
} from '../constants/assessment-type.constants';
import {
  AI_QUESTION_TYPES,
  toAiQuestionType,
} from '@/modules/assessment/dto/assessment.dto';
import { TOKEN_COST } from '@/core/ai/constants';
import { buildChunkPrompt } from '@/core/ai/prompt-builder.util';

// TICK-ASSESS-005. The two bugs this pins:
//
//  1. Manual-only types (`behavior`, `participation`, …) were selectable under
//     System-Graded. The AI auto-graded them and `grade-core.service.ts`
//     averaged the result by weight — a semantically wrong category entering the
//     authoritative grade.
//  2. The wizard sent `true_or_false` but the AI layer keyed on `true_false`.
//     The call site used an unchecked `as` cast, so the mismatch compiled and
//     then failed at runtime: the prompt-builder lookup missed and fell back to
//     the `identification` format, which the UI then rendered as Multiple Choice.
describe('assessment type gradability + question-type unification (TICK-ASSESS-005)', () => {
  const MANUAL_ONLY = [
    'participation',
    'behavior',
    'attendance',
    'performance_task',
  ];
  const SYSTEM_GRADABLE = [
    'written_work',
    'quarterly_assessment',
    'exam',
    'quiz',
    'assignment',
    'project',
    'recitation',
    'activity',
    'custom',
    'other',
  ];

  describe('system vs manual-only split', () => {
    it.each(MANUAL_ONLY)('"%s" is manual-only', (t) => {
      expect(isSystemGradable(t)).toBe(false);
      expect(MANUAL_ONLY_TYPES).toContain(t);
    });

    it.each(SYSTEM_GRADABLE)('"%s" is system-gradable', (t) => {
      expect(isSystemGradable(t)).toBe(true);
      expect(SYSTEM_GRADABLE_TYPES).toContain(t);
    });

    it('the two sets partition all 14 types with no overlap', () => {
      const manual = [...MANUAL_ONLY_TYPES].sort();
      const system = [...SYSTEM_GRADABLE_TYPES].sort();
      expect(new Set([...manual, ...system]).size).toBe(14);
      for (const t of manual) expect(system).not.toContain(t);
      expect([...manual, ...system].sort()).toEqual(
        [...ASSESSMENT_TYPE_VALUES].sort(),
      );
    });

    it('fails closed for unknown and legacy types', () => {
      // 'manual' is the legacy scheme-component marker, NOT an assessment type,
      // so it must never be treated as auto-gradable.
      expect(isSystemGradable('manual')).toBe(false);
      expect(isSystemGradable('nonsense')).toBe(false);
      expect(isSystemGradable('')).toBe(false);
    });
  });

  describe('true_or_false unification', () => {
    it('passes every AI-generatable type through verbatim', () => {
      for (const t of AI_QUESTION_TYPES) {
        expect(toAiQuestionType(t)).toBe(t);
      }
    });

    it('keeps true_or_false intact (the T/F bug)', () => {
      expect(toAiQuestionType('true_or_false')).toBe('true_or_false');
    });

    it('throws on a non-AI type instead of casting it through', () => {
      // The old `as QuestionBlueprint['type']` cast silently accepted all of these.
      expect(() => toAiQuestionType('manual')).toThrow(
        /cannot be generated by the AI/,
      );
      expect(() => toAiQuestionType('true_false')).toThrow();
      expect(() => toAiQuestionType('behavior')).toThrow();
    });

    it('TOKEN_COST covers every AI question type', () => {
      // A miss silently fell back to 150, corrupting chunk sizing and maxTokens.
      for (const t of AI_QUESTION_TYPES) {
        expect(typeof TOKEN_COST[t]).toBe('number');
      }
    });

    it('TOKEN_COST has no stale true_false key', () => {
      expect(TOKEN_COST['true_false']).toBeUndefined();
    });

    it('buildChunkPrompt renders the True/False format, not identification', () => {
      const prompt = buildChunkPrompt(
        'LESSON BODY',
        'true_or_false',
        ['Section A'],
        '1-2',
        2,
        [1, 2],
      );
      expect(prompt).toContain('"type": "true_or_false"');
      expect(prompt).toContain('"answer": "True"');
      expect(prompt).toContain('exactly "True" or "False"');
      // The identification example must not leak in.
      expect(prompt).not.toContain('short specific correct answer');
      expect(prompt).not.toContain('"type": "identification"');
    });

    it('buildChunkPrompt uses each type\'s own example', () => {
      for (const t of AI_QUESTION_TYPES) {
        const prompt = buildChunkPrompt('L', t, ['S'], '1-1', 1, [1]);
        expect(prompt).toContain(`"type": "${t}"`);
      }
    });

    it('buildChunkPrompt throws on an unknown type rather than falling back', () => {
      expect(() =>
        buildChunkPrompt('L', 'bogus' as never, ['S'], '1-1', 1, [1]),
      ).toThrow(/No prompt format defined/);
    });
  });
});
